import './globals.scss'
import { Inter } from 'next/font/google'
import style from "../../styles/header.module.scss";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SAE2.04',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
      <header id={style.header}>
            <h1><Link href="/">Analyse Vélib</Link></h1>
            <nav>
                <ul>
                    <li><Link href="/">Accueil</Link></li>
                    <li><Link href="/map">Carte</Link></li>
                </ul>
            </nav>
        </header>
        <div id="background"></div>
        {children}
        </body>
    </html>
  )
}
